### ISSUE TITLE
Compatibility with Pale Moon

### ISSUE THREAD

**Issue by VLM1** [gijsk/chromelist#3]
Hi there. Have you considered making your Chrome List extension available for Pale Moon users? (PM is a Firefox fork from Fx 24.) Would you consider it? I ask, because your version #s jump from 3 to 42 (in the AMO version history), so there is no "back version" to install. Also, since Mozilla is deprecating XUL, Toolkit, etc. Pale Moon may end up being the only Firefox-like browser left for which existing Firefox extensions can be made to work. 

Thank you for you consideration.

**Comment by gijsk** [comment]
I don't think this is a good idea. The current codebase probably won't work with the JS support from Fx 24. Once XUL-based add-ons are deprecated the reason for this add-on to exist also mostly goes away, because the main usecase right now is add-on devs who want to look at the XUL-based "filesystem" provided by chrome:// URIs. That won't be necessary in the new webextensions world.

**Comment by VLM1** [comment]
I understand, and thank you for responding.

It will continue to matter in Pale Moon, which will retain the existing
XUL-based "file system", as you describe it. The reason for the extension
will not diminish at all. This is the reason for my request, so that the
fruits of your hard and generous labor will not be lost.

Pale Moon is a true fork. Unlike the other Firefox "forks" of which I am
aware, which are little more than minor modifications of Firefox, the Pale
Moon dev team is in the process of a major renovation of the product's
back end. My understanding is that the JS support in Firefox 24 has been
(or is being) updated/upgraded considerably. But I am a user, not a
developer, so I cannot speak with authority on this. Would you be willing
to interact with someone on the dev team, just enough to explore this
specific question?

Kind regards,
Elchanan

On Sat, August 20, 2016 5:51 am, Gijs wrote:
I don't think this is a good idea. The current codebase probably won't
work with the JS support from Fx 24. Once XUL-based add-ons are deprecated
the reason for this add-on to exist also mostly goes away, because the
main usecase right now is add-on devs who want to look at the XUL-based
"filesystem" provided by chrome:// URIs. That won't be necessary in the
new webextensions world.

##
