### ISSUE TITLE
Support for Pale Moon

### ISSUE THREAD

**Issue by jobbautista9** [gijsk/chromelist#4]
Can you consider targeting this extension for Pale Moon too? It works perfectly there. Thanks!

**Comment by gijsk** [comment]
I don't have time to work on this extension. It already has a toolkit@ target which should be sufficient for pale moon, too. I'd take a PR to change the maxversion for toolkit@, but I don't want to add other, specific targets because it implies a level of testing that I can't commit to.

**Comment by jobbautista9** [comment]
The reason I asked is because extensions that only target Firefox will eventually not be supported in Pale Moon. If your concern is about testing, I can volunteer testing for Pale Moon support. :) After all, I depend on it when I'm working with add-ons.
